targets:
  $default:
    builders:
      inherited_data:
        options:
        # generate_for:
        #   - inherited_data_example.dart

      source_gen|combining_builder:
        options:
          ignore_for_file:
          - lint_a
          - lint_b