name: inherited_data_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  inherited_data:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 

flutter:
  uses-material-design: false