name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  inherited_data:
    path: ../

dev_dependencies:
  build_runner:
  lints: ^2.0.0
  test: ^1.21.0
