name: inherited_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/Wizards-Pub/inherited_data

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  build:
  built_collection:
  analyzer: 
  meta:
  source_gen: ^1.2.7
  code_builder: ^4.4.0
  dart_style: ^2.3.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0