targets:
  $default:
    builders:
      inherited_data|inherited_data:
        enabled: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  inherited_data:
    import: "package:inherited_builder/src/builder.dart"
    builder_factories: ["inheritedBuilder"]
    build_extensions: {".dart": [".inherited.dart"]}
    auto_apply: dependents
    build_to: source
